---

- name: install memcached
  yum:
    name: memcached
    state: present

- name: put memcached config file
  template:
    src: memcached-sysconfig.j2
    dest: /etc/sysconfig/memcached
    owner: root
    group: root
    mode: "0644"
  notify: restart memcached
